# Copyright 2019-2020 Fujitsu Laboratories Ltd.
# SPDX-License-Identifier: Apache-2.0
version: "3"
services:
  geth1:
    container_name: geth1.12.0
    image: ethereum/client-go:v1.12.0
    tty: true
    volumes:
      - "$PWD/data-geth1:/root/data"
      - "$PWD/data-geth1/keystore:/root/data/keystore"
      - "$PWD/data-geth1/genesis.json:/root/data/genesis.json" # mount genesis.js from host
    # working_dir: /root
    ports:
      - 8545:8545/tcp # RPC - HTTP
      - 8546:8546/tcp # RPC - WS
    expose:
      - 8545/tcp # RPC - HTTP
      - 8546/tcp # RPC - WS
    networks:
      - geth1net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # following parameters are given to geth
    command: >
      --datadir=/root/data
      --networkid 10
      --nodiscover
      --http
      --http.addr "0.0.0.0"
      --http.port "8545"
      --http.corsdomain "*"
      --http.vhosts "*"
      --http.api "eth,personal,web3,net"
      --ws
      --ws.addr "0.0.0.0"
      --ws.port "8546"
      --ws.api "eth,personal,web3,net"
      --ws.origins "*"
      --unlock 0,1,2,3,4
      --mine
      --password "/dev/null"
      --allow-insecure-unlock
      --miner.etherbase 0x6A2EC8c50BA1a9cE47c52d1cb5B7136Ee9d0cCC0
networks:
  geth1net:
    external: true
